openapi: 3.0.0
info:
  title: Notes API - aplikacja umożliwiająca dodawanie i zarządzanie notatkami
  description: API aplikacji wspomagajace zarządzanie notatkami użytkownika. Jest to aplikacja webowa, która umożliwia dodawanie, usuwanie oraz wyświetlanie wszystkich notatek. Ułatwia zarządzanie własnymi notatkami
  version: 1.0.0
servers:
  - url: https://localhost:8080
paths:
  /notes:
    get:
      summary: Retrieve a list of notes
      operationId: listNotes
      responses:
        '200':
          description: A list of notes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      summary: Create a new note
      operationId: createNote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteInput'
      responses:
        '201':
          description: The created note
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
  /notes/{noteId}:
    parameters:
      - name: noteId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Retrieve a specific note by ID
      operationId: getNote
      responses:
        '200':
          description: The requested note
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '404':
          description: Note not found
    patch:
      summary: Update an existing note
      operationId: updateNote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteInput'
      responses:
        '200':
          description: The updated note
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '404':
          description: Note not found
    delete:
      summary: Delete a note by ID
      operationId: deleteNote
      responses:
        '204':
          description: Note deleted
        '404':
          description: Note not found
components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123
        title:
          type: string
          example: My note
        content:
          type: string
          example: Lorum ipsum
        created_at:
          type: string
          format: date-time
          example: 01-02-2023 23:33:02
        updated_at:
          type: string
          format: date-time
          example: 01-02-2023 13:09:12
      required:
        - title
        - content
    NoteInput:
      type: object
      properties:
        title:
          type: string
          example: My note
        content:
          type: string
          example: Lorum ipsum
      required:
        - title
        - content